// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function HideWindow():Promise<void>;

export function IsPinned():Promise<boolean>;

export function LoadNotes():Promise<main.NotesFile>;

export function MinimizeWindow():Promise<void>;

export function NewNote():Promise<void>;

export function QuitApp():Promise<void>;

export function SaveNotes(arg1:main.NotesFile):Promise<void>;

export function ShowWindow():Promise<void>;

export function TogglePin():Promise<boolean>;

export function ToggleWindow():Promise<void>;
