// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsPinned() {
  return window['go']['main']['App']['IsPinned']();
}

export function LoadNotes() {
  return window['go']['main']['App']['LoadNotes']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function NewNote() {
  return window['go']['main']['App']['NewNote']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveNotes(arg1) {
  return window['go']['main']['App']['SaveNotes'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TogglePin() {
  return window['go']['main']['App']['TogglePin']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
