// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function IsPinned():Promise<boolean>;

export function LoadNotes():Promise<main.NotesFile>;

export function MinimizeWindow():Promise<void>;

export function Quit():Promise<void>;

export function SaveNotes(arg1:main.NotesFile):Promise<void>;

export function TogglePin():Promise<boolean>;
