// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsPinned() {
  return window['go']['main']['App']['IsPinned']();
}

export function LoadNotes() {
  return window['go']['main']['App']['LoadNotes']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveNotes(arg1) {
  return window['go']['main']['App']['SaveNotes'](arg1);
}

export function TogglePin() {
  return window['go']['main']['App']['TogglePin']();
}
